
import static java.lang.Double.parseDouble;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Walton Passion
 */
public class Currency extends javax.swing.JFrame {
    private Object text1;

    /**
     * Creates new form Currency
     */
    public Currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtfrom = new javax.swing.JComboBox();
        txtto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        x = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Enter the amount");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("From");

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("To");

        txtamount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        txtfrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "Bangladeshi Taka", "Indian Rupees" }));

        txtto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangladeshi Taka", "Indian Rupees", "USD" }));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Convert");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        x.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText(" Exit ");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 51, 0));
        txt1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Currency", "Temperature", "Weight", "Area", " ", " " }));
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtamount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       Double tot;
      String box1 = txtfrom.getSelectedItem().toString();
      String box2 = txtto.getSelectedItem().toString();
      Double amount = parseDouble(txtamount.getText());
      String text = "From  "+box1+" to "+box2+"  is ";
      String textError = "You put an invalid data";

      
      

      if(box1 == "USD" && box2 == "Bangladeshi Taka"){
        tot = amount * 93.45;
//        JOptionPane.showMessageDialog(this,text+tot.toString());
        JOptionPane.showMessageDialog(this,text+tot+" Taka");
        x.setText("  "+tot+" Taka");
      }
     else if(box1 == "USD" && box2 == "Indian Rupees"){
        tot = amount * 79.01;
        JOptionPane.showMessageDialog(this,text+tot+" Rupees");
        x.setText("  "+tot+" Rupees");
      }
      
       else if(box1 == "Bangladeshi Taka" && box2 == "USD"){
        tot = amount / 93.45;
        JOptionPane.showMessageDialog(this,text+tot+" $");
        x.setText("  "+tot+" $");
      }
      
       else if(box1 == "Indian Rupees" && box2 == "USD"){
        tot = amount * 79.01;
        JOptionPane.showMessageDialog(this,text+tot+" $");
        x.setText("  "+tot+" $");
      }
      
        else if(box1 == "Indian Rupees" && box2 == "Bangladeshi Taka"){
        tot = amount * 1.18;
        JOptionPane.showMessageDialog(this,text+tot+" Taka");
        x.setText("  "+tot+" Taka");
      }
         else if(box1 == "Bangladeshi Taka" && box2 == "Indian Rupees"){
        tot = amount / 1.18;
        JOptionPane.showMessageDialog(this,text+tot+" Rupees");
        x.setText("  "+tot+" Rupees");
      }
         else if(box1 == "Indan Rupees" && box2 == "Indian Rupees"){
//        tot = amount * 93.45;
//        JOptionPane.showMessageDialog(this,text+tot.toString());
        JOptionPane.showMessageDialog(this,amount+" Rupees");
        x.setText("  "+amount+" Rupees");
      }
        else if(box1 == "USD" && box2 == "USD"){
//        tot = amount * 93.45;
//        JOptionPane.showMessageDialog(this,text+tot.toString());
       JOptionPane.showMessageDialog(this,amount+" $");
        x.setText("  "+amount+" $");
      }
         else  if(box1 == "Bangladeshi Taka" && box2 == "Bangladeshi Taka"){
//        tot = amount * 93.45;
//        JOptionPane.showMessageDialog(this,text+tot.toString());
        JOptionPane.showMessageDialog(this,amount+" Taka");
        x.setText("  "+amount+" Taka");
      }
      else if(box1 == "Fahrenheit" && box2 == "Celsius"){
       
         tot = ((amount - 32)* 5/9);
        JOptionPane.showMessageDialog(this,tot+" degree C");
        x.setText("  "+tot+" degree C");
      }
      
       else if(box1 == "Celsius" && box2 == "Fahrenheit"){
//        tot = (9/5)*(amount - 32);
           tot = (amount * 9/5 +32);
        JOptionPane.showMessageDialog(this,tot+" degree F");
        x.setText("  "+tot+" degree F");
      }
       
       else if(box1 == "Celsius" && box2 == "Celsius"){
//        tot = ((amount*9/5) + 32);
        JOptionPane.showMessageDialog(this,amount+" degree C");
        x.setText("  " +amount+" degree C");
      }
        else if(box1 == "Fahrenheit" && box2 == "Fahrenheit"){
//        tot = ((amount*9/5) + 32);
        JOptionPane.showMessageDialog(this,amount+" degree F");
        x.setText("  "+amount+" degree F");
      }
         else{
             JOptionPane.showMessageDialog(this,textError);
             x.setText("invalid");
         }
      
     

      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
   
      String choice = txt1.getSelectedItem().toString();

  

      
      switch(choice) {
      case "Currency":{
        txtfrom.removeAllItems();
        txtfrom.addItem("USD"); 
        txtfrom.addItem("Bangladeshi Taka"); 
        txtfrom.addItem("Indian Rupees"); 
          
        txtto.removeAllItems();
        txtto.addItem("Bangladeshi Taka"); 
        txtto.addItem("Indian Rupees"); 
        txtto.addItem("USD");  

        break;}

//      case "Area" :
//        txtfrom.removeAllItems();
//        txtfrom.addItem("Bangladeshi Taka"); 
//        txtfrom.addItem("Indian Rupees"); 
//        txtfrom.addItem("USD");  
//        Op = "Area";
//        break;


      case "Temperature":
        txtfrom.removeAllItems();
        txtfrom.addItem("Fahrenheit"); 
        txtfrom.addItem("Celsius"); 
        txtto.removeAllItems();
        txtto.addItem("Celsius"); 
        txtto.addItem("Fahrenheit"); 
        break;

//      case "Weight":
//        txtfrom.removeAllItems();
//        txtfrom.addItem("Bangladeshi Taka"); 
//        txtfrom.addItem("Indian Rupees"); 
//        txtfrom.addItem("USD");  
//              Op = "Weight";
//        break;
      
      default:
        txtfrom.removeAllItems();
        txtfrom.addItem("USD"); 
        txtfrom.addItem("Bangladeshi Taka"); 
        txtfrom.addItem("Indian Rupees"); 
      
        
        txtto.removeAllItems();
        txtto.addItem("Bangladeshi Taka"); 
        txtto.addItem("Indian Rupees"); 
        txtto.addItem("USD");  
  
        break;

    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox txt1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JComboBox txtfrom;
    private javax.swing.JComboBox txtto;
    private javax.swing.JTextField x;
    // End of variables declaration//GEN-END:variables
}
